version: 2
updates:
    - package-ecosystem: npm
      directory: "/"
      schedule:
          interval: "daily"
          time: "19:00"
          timezone: "Asia/Shanghai"
      ignore:
          - dependency-name: "webpack"
            versions:
                - ">= 5.0.0"
