version: 2
updates:
    - package-ecosystem: npm
      directory: "/"
      schedule:
          interval: daily
      ignore:
          - dependency-name: "webpack"
            versions:
                - ">= 5.0.0"
