version: 2
updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: monthly
      time: "04:00"
      timezone: Asia/Shanghai
    ignore:
      - dependency-name: semantic-release
        versions:
          - ">= 21.0.1"
      - dependency-name: "@commitlint/cli"
        versions:
          - ">= 19.0.0"
      - dependency-name: "@commitlint/config-conventional"
        versions:
          - ">= 19.0.0"
      - dependency-name: "eslint"
        versions:
          - ">= 9.0.0"
      - dependency-name: "parse-json"
        versions:
          - ">= 6.0.0"
